import React from 'react'

export const ThumbnailData = [
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
    {
        "image": "./video.svg",
        "avatar": "./avatar.svg",
        "title": "Lorem ipsum dolor sit amet, consecte adipiscing elit",
        "youtuber": "James Gouse",
        "time": "15K Views .1 week ago",
    },
]