import React from 'react'

export const videoData = [
    {
        'channelID':'UC22go5LdQEw-iDuxFb4C0hw',
        'videoId': 'ZGElK1N_Xdk',
        'title':`Cat Can't Accept The Fact That He's Fat`,
        'channel-name':'SBS TV동물농장x애니멀봐',
        'views':'13M views Dec 4, 2020',
        'videoThumbnail': 'https://i.ytimg.com/vi/ZGElK1N_Xdk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC-RWEcIFnXMwuBZYxvPZiRHl6Ctw',
        'videoProfile': 'https://yt3.ggpht.com/VovCAMdmNvWsAlDenNBzS6rDSUg636bPBKCA5EIup1o2Ny7DbUQlS88F4I7C-cqB5ckbiMr7=s88-c-k-c0x00ffffff-no-rj',
        'commentAvatar': 'https://yt3.ggpht.com/ytc/APkrFKaylJ4G0J7V_ugValHwglVza4rvy1DLIlsfGIGWDw=s88-c-k-c0x00ffffff-no-rj',
        'commentName': '@Raymak',
        'commentDate': '1 year ago',
        'comment': 'Cat clearly not happy with his weight but super happy with food',
        'commentLike': '13K',
    },
    {
        'channelID':'UC22go5LdQEw-iDuxFb4C0hw',
        "videoId": 'mULvGLOKVCA',
        'title':'Meet This Buddhist Cat Who Will Find Buddha InsvideoIde You',
        'channel-name':'SBS TV동물농장x애니멀봐',
        'views':'8.2M views 3 years ago',
        'videoThumbnail':'https://i.ytimg.com/vi/mULvGLOKVCA/hq720.jpg?sqp=-…AFwAcABBg==&rs=AOn4CLAjJThHe-kpjmM0HR-D_VoIcMuc5Q',
        'videoProfile': 'https://yt3.ggpht.com/VovCAMdmNvWsAlDenNBzS6rDSUg636bPBKCA5EIup1o2Ny7DbUQlS88F4I7C-cqB5ckbiMr7=s88-c-k-c0x00ffffff-no-rj',
        'commentAvatar': 'https://yt3.ggpht.com/WlALZ7isVY86yzhzNBODLRuscRt6BVO_kq4cTWdqN9WA0MrGmjdzraZ7J1AIQCbLPrSKJIuw-S0=s88-c-k-c0x00ffffff-no-rj',
        'commentName': '@jlorrainek',
        'commentDate': '2 years ago',
        'comment': `I've always thought that jumping spiders were smarter than the others. They just are so AWARE.`,
        'commentLike': '4.7K',
    },
    {
        'channelID':'UCwmZiChSryoWQCZMIQezgTg',
        "videoId": 'q3uXXh1sHcI',
        'title':`Baby Penguin Tries To Make Friends | Snow Chick: A Penguin's Tale | BBC Earth`,
        'channel-name':'BBC Earth',
        'views':'9.2M views  1 year ago',
        'videoThumbnail':'https://i.ytimg.com/vi/q3uXXh1sHcI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDMM3K8Wn34mnp5SXhPHj04RGbTew',
        'videoProfile':'https://yt3.ggpht.com/hUrDI5Q0fIt4sWIfNkDYkXkg3bmSfw2xgJvKYq5NKmlqvUDYmJzagMaPMkArbZyD4CXP1C08=s176-c-k-c0x00ffffff-no-rj-mo',
    },
    {
        'channelID':'UC22go5LdQEw-iDuxFb4C0hw',
        "videoId": 'YFzgnqnA_tY',
        'title':'I’m A 90 days Old African Spurred Tortoise [I’m THE Baby 39th lead]',
        'channel-name':'SBS TV동물농장x애니멀봐',
        'views':'41K views  1 month ago',
        'videoThumbnail':'https://i.ytimg.com/vi/YFzgnqnA_tY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDfE_z1piovVFvY7h5A3k_ISEZoZA',
        'videoProfile': 'https://yt3.ggpht.com/VovCAMdmNvWsAlDenNBzS6rDSUg636bPBKCA5EIup1o2Ny7DbUQlS88F4I7C-cqB5ckbiMr7=s88-c-k-c0x00ffffff-no-rj',
    },
    {
        'channelID':'UC22go5LdQEw-iDuxFb4C0hw',
        "videoId": 'A7wP87m-Hy4',
        'title':'Story of How Cat That Near Death Became a College Student',
        'channel-name':'SBS TV동물농장x애니멀봐',
        'views':'4.6M views  9 months ago',
        'videoThumbnail':'https://i.ytimg.com/vi/A7wP87m-Hy4/hq720.jpg?sqp=-…AFwAcABBg==&rs=AOn4CLCcmvH5OY4ZZLXu39eoYqbGDdy3Fw',
        'videoProfile': 'https://yt3.ggpht.com/VovCAMdmNvWsAlDenNBzS6rDSUg636bPBKCA5EIup1o2Ny7DbUQlS88F4I7C-cqB5ckbiMr7=s88-c-k-c0x00ffffff-no-rj',
    },
    {
        'channelID':'UCCj956IF62FbT7Gouszaj9w',
        "videoId": 'minuhFCt62k',
        'title':'How many brains does an octopus have? | Spy in the Ocean',
        'channel-name':'BBC',
        'views':'361K views  3 months ago',
        'videoThumbnail':'https://i.ytimg.com/vi/minuhFCt62k/hq720.jpg?sqp=-…AFwAcABBg==&rs=AOn4CLAykGluLE4Vwrtk24Gt-HsoMNADfg',
        'videoProfile':'https://yt3.ggpht.com/Y_iNjNBFP6bpHwT2hAHaLj7J3po22sGjwlR6mn26PWRp2IFesRAeNQEpSuh9xFiG8R57OOE83DE=s68-c-k-c0x00ffffff-no-rj',
    },
    {
        'channelID':'UCwmZiChSryoWQCZMIQezgTg',
        "videoId": 'uHyYtcMZYGs',
        'title':'Best Spider Moments | Top 5 | BBC Earth',
        'channel-name':'BBC Earth',
        'views':'5.6M views  2 years ago',
        'videoThumbnail':'https://i.ytimg.com/vi/uHyYtcMZYGs/hq720.jpg?sqp=-…AFwAcABBg==&rs=AOn4CLBjntuPJF-Yu0EryX5y5v-Z654PKQ',
        'videoProfile': 'https://yt3.ggpht.com/hUrDI5Q0fIt4sWIfNkDYkXkg3bmSfw2xgJvKYq5NKmlqvUDYmJzagMaPMkArbZyD4CXP1C08=s176-c-k-c0x00ffffff-no-rj-mo',
    },
    {
        'channelID':'UCsooa4yRKGN_zEE8iknghZA',
        "videoId": 'VLkKiVIBxXU',
        'title':'Why the octopus brain is so extraordinary - Cláudio L. Guerra',
        'channel-name':'TED-ED',
        'views':'5.6M views  2 years ago',
        'videoThumbnail': 'https://i.ytimg.com/vi/VLkKiVIBxXU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDtukga13jklh7DSqYu_Olpwm2DiA',
        'videoProfile': 'https://yt3.ggpht.com/HjXKmDGoAp6b-JdGYpqJYYeN4S_CMpD_kqWvldpN53cbzn-i73t6mVNo8mNki-xLPwi0BVSFi-o=s176-c-k-c0x00ffffff-no-rj-mo',
    }

] 